version: '3.8'

volumes:
  lesson_50_storage_data:

services:
  database:
    image: postgres:14.3-alpine
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - lesson_50_storage_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
