version: '3.0'

services:
  mongo:
    container_name: mongo-test
    image: mongo:4.2-bionic
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - '10000:27017'
    env_file:
      - .env
