# FROM node:18.3-alpine

# WORKDIR /src
# COPY package*.json /src
# RUN npm ci
# COPY . .

# CMD ["npm", "run", "dev"]

FROM alpine

RUN apk --no-cache add curl
RUN apk add --update nodejs npm

WORKDIR /src
COPY package*.json .
RUN npm install
COPY . .

CMD ["npm", "run", "prod"]
